services:
  api:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: .
    ports:
      - "80:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - PORT=3000
    restart: unless-stopped
